version: '3.7'

volumes:
    my-datavolume: {}

services:
    spring_boot:
        image: espada1317/spring_boot_blog
        env_file: ./.env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        restart:
            always
        depends_on:
            - db
        links:
            - db:db_mysql
        environment:
            SPRING_DATASOURCE_URL : jdbc:mysql://db:$MYSQLDB_LOCAL_PORT/$MYSQLDB_DATABASE?createDatabaseIfNotExist=TRUE
            SPRING_DATASOURCE_USERNAME : $MYSQLDB_USER
            SPRING_DATASOURCE_PASSWORD : $MYSQLDB_ROOT_PASSWORD
            SPRING_JPA_HIBERNATE_DDL-AUTO : update
            SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT : org.hibernate.dialect.MySQL5InnoDBDialect

    db:
        image: mysql:5.7
        env_file: ./.env
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
            - MYSQL_USER=$MYSQLDB_USER
            - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD
        volumes:
            - my-datavolume:/var/lib/mysql

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        env_file: ./.env
        ports:
            - $PHPMYADMIN_LOCAL_PORT:$PHPMYADMIN_DOCKER_PORT
        restart: always
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_USERNAME: $MYSQLDB_ROOT_USERNAME
            SPRING_DATASOURCE_PASSWORD: $MYSQLDB_ROOT_PASSWORD
