version: '3.7'

services:
    spring_boot:
        build:
            context: .
            dockerfile: Dockerfile
        env_file: ./.env
        ports:
            - $SPRING_LOCAL_PORT:$SPRING_DOCKER_PORT
        restart:
            always
        depends_on:
            - db
        links:
            - db:db_mysql
        environment:
            SPRING_DATASOURCE_URL : jdbc:mysql://db:3306/blog_db?createDatabaseIfNotExist=TRUE
            SPRING_DATASOURCE_USERNAME : espada
            SPRING_DATASOURCE_PASSWORD : pass
            SPRING_JPA_HIBERNATE_DDL-AUTO : update
            SPRING_JPA_PROPERTIES_HIBERNATE_DIALECT : org.hibernate.dialect.MySQL5InnoDBDialect

    db:
        image: "mysql:5.7"
        env_file: ./.env
        ports:
            - $MYSQLDB_LOCAL_PORT:$MYSQLDB_DOCKER_PORT
        restart: always
        environment:
            - MYSQL_ROOT_PASSWORD=$MYSQLDB_ROOT_PASSWORD
            - MYSQL_DATABASE=$MYSQLDB_DATABASE
            - MYSQL_USER=$MYSQLDB_USER
            - MYSQL_PASSWORD=$MYSQLDB_ROOT_PASSWORD

    #service 2: definition of phpMyAdmin
    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        ports:
            - "8082:80"
        restart: always
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: pass
