version: '3.3'

services:
    db:
        image: mysql:5.7
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=blog_db
        command:
            - mysqld --skip-grant-tables
        ports:
            - "3306:3306"
        restart: always

    phpmyadmin:
        image: phpmyadmin/phpmyadmin:latest
        container_name: my-php-myadmin
        ports:
            - "8082:80"
        restart: always

        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD:

    customerservice:
        image: spring-boot-note
        container_name: spring-boot-note-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8080:8080"
        restart:
            always
        depends_on:
            - db
        environment:
            SPRING_DATASOURCE_URL: jdbc:mysql://mysql-db:3306/blog_db?createDatabaseIfNotExist=true
            SPRING_DATASOURCE_USERNAME: root
            SPRING_DATASOURCE_PASSWORD: root


#version: '3.7'
#
#services:
#    app-server:
#        build:
#            context: spring-boot-note-app
#            dockerfile: Dockerfile
#        ports:
#            - "8080:8080"
#        restart: always
#        depends_on:
#            - db
#        environment:
#            SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/blog_db
#            SPRING_DATASOURCE_USERNAME: root
#            SPRING_DATASOURCE_PASSWORD: pass
#        networks:
#            - backend
#
#    db:
#        image: mysql:5.7
#        ports:
#            - "3306:3306"
#        restart: always
#        environment:
#            MYSQL_DATABASE: blog_db
#            MYSQL_USER: root
#            MYSQL_PASSWORD: user
#            MYSQL_ROOT_PASSWORD: root
#        volumes:
#            - db-data:/var/lib/mysql
#        networks:
#            - backend
